using Microsoft.CodeAnalysis;

namespace CombiningModels.SourceGeneration
{
    [Generator]
    public class ExampleSourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            // Find the main method
            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            // Build up the source code
            var source = $@"// <auto-generated/>
//Тут необходимо указать необходимые using's для генерируемого кода.
using System;

namespace {mainMethod.ContainingNamespace.ToDisplayString()}
{{
    public static partial class {mainMethod.ContainingType.Name}
    {{
        static partial void ExampleGeneration(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
    }}
}}";
            var typeName = mainMethod.ContainingType.Name;

            // Add the source code to the compilation
            context.AddSource($"{typeName}.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            //В данном примере не требуется.
        }
    }
}